CREATE PROCEDURE GetFoodForAnimal
    @AnimalId INT
AS

    SELECT FOOD_ID, f.NAME as FOOD_NAME, DESCRIPTION, f.ANIMAL_ID, a.NAME as ANIMAL_NAME, NUMBER_OF_PACKAGES_IN_STORAGE, PACKAGE_WEIGHT_IN_KG, EARLIEST_EXPIRATION_DATE, f.FOOD_KIND_ID, fk.NAME as FOOD_KIND_NAME FROM Food f INNER JOIN Animals a ON f.ANIMAL_ID = a.ANIMAL_ID INNER JOIN FoodKind fk on f.FOOD_KIND_ID = fk.FOOD_KIND_ID
    WHERE f.ANIMAL_ID = @AnimalId ORDER BY PACKAGE_WEIGHT_IN_KG DESC
GO


CREATE PROCEDURE CheckFoodData
AS
   SELECT DISTINCT a.NAME as AnimalName,    
       COUNT(f.FOOD_ID) OVER (PARTITION BY a.ANIMAL_ID) AS NumberOfDifferentFood, 
       MIN(f.PRICE) OVER (PARTITION BY a.ANIMAL_ID) AS MinimumFoodPrice,  
       MAX(f.PRICE) OVER (PARTITION BY a.ANIMAL_ID) AS MaximumFoodPrice,  
       AVG(f.PRICE) OVER (PARTITION BY a.ANIMAL_ID) AS AverageFoodPrice
	FROM Food AS f 
	JOIN Animals AS a  ON f.ANIMAL_ID = a.ANIMAL_ID 	
	JOIN Toys AS t ON t.ANIMAL_ID = a.ANIMAL_ID  
	ORDER BY a.NAME;  
GO
